quarkus:
  devservices:
    enabled: false
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jdbc:
      url: jdbc:postgresql://localhost:5432/ET
    devservices:
      enabled: false
  hibernate-orm:
    database:
      default-schema: public
    schema-management:
      strategy: validate
  log:
    console:
      level: INFO

bcrypt:
  work-factory: 12